### ISSUE TITLE
help me!! To use function EntitiesCreateRequest

### ISSUE THREAD

**Issue by sdwkn** [mlabouardy/dialogflow-go-client#1]
If you use Japanese for Entries of EntityCreateRequest, garbled characters will occur, but are there any findings?
If lang is not set in the specification of dialogflow, it says that the default language will be used, but do you know something?

**Comment by mlabouardy** [comment]
@sdwkn you found a solution ?

**Comment by sdwkn** [comment]
@mlabouardy 
Thank you for your reply.
I could use it after adding character code to the content type!

Let me also tell everyone.

**Comment by mlabouardy** [comment]
thank you for your feedback !
