### ISSUE TITLE
Go get : multiple-value uuid.NewV4() in single-value context

### ISSUE THREAD

**Issue by seblegall** [mlabouardy/dialogflow-go-client#13]
Hi,

I have some trouble go-getting your client using Golang version 1.9.2. Here is the error message : 

```sh
$ go get -u github.com/mlabouardy/dialogflow-go-client
# github.com/mlabouardy/dialogflow-go-client
../../mlabouardy/dialogflow-go-client/apiai.go:47:32: multiple-value uuid.NewV4() in single-value context
```

For now, I just want to test dialogflow with my own chat server so I will build the query myself. But if I find some time during the next week I'll try to figure out what's going wrong.

**Comment by seblegall** [comment]
Shame on me. I just have seen the PR open 12 days ago on the same subject. My bad for the issue.

**Comment by mlabouardy** [comment]
merged https://github.com/mlabouardy/dialogflow-go-client/pull/12
