### ISSUE TITLE
Integer in Result.parameters Error

### ISSUE THREAD

**Issue by dImrich** [mlabouardy/dialogflow-go-client#5]
With action entity @sys.number dialogflow returns integer to parameters json and parsing json to string array cause error.

**Error**
`json: cannot unmarshal string into Go struct field Result.parameters of type []string`

**Comment by DamianImrich** [comment]
Another error

`json: cannot unmarshal string into Go struct field Result.parameters of type []string
exit status 1
`

**Comment by mlabouardy** [comment]
merged https://github.com/mlabouardy/dialogflow-go-client/pull/10
